import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Twitter App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex mx-auto xl:max-w-7xl lg:max-w-5xl md:max-w-3xl">
                    <Navbar />
                    <div className="flex-1">{children}</div>
                </div>
            </body>
        </html>
    );
}
